### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by scottzirkel** [javisperez/tailwindcolorshades#3] opened 2018-10-15 20:40 UTC
It would be nice to be able to paste the hex instead of manually typing it. Not sure why I can't paste it, or if we're not supposed to be able to, but it is kind of a pain, especially when I'm trying different colors out.

Another small tweak would be to list the colors from darkest to lightest, as they are in the tailwind.js file. That's a minor issue though.

**Comment by javisperez** [comment] 2018-10-16 13:06
Hey, @scottzirkel thanks for the issue.

About the pasting bug, I'm not able to reproduce, could you please give me some more info about it? like, what browser are you using? are we talking only about the color hex code or also the color name? in my case, I am fully able to copy and paste from/to both inputs, using either `cmd+c` or the right-click menu.

Also, for the colors, I didn't notice until now (and thank you for that!) that tailwind.js changed the way colors are shown, so I might need to update that :) the idea is to mimic Tailwind's original color styles, I just wasn't aware of this "new" style, thanks again!

**Comment by scottzirkel** [comment] 2018-10-17 21:33
You bet! So I'm trying to paste `cmd+c` in Mojave (same issue was in High Sierra as well) with Firefox, Safari, and ~Chrome~. All running the latest versions as of today. I can paste into the color name input, but not the hex input.

Edit: Just tried it again in Chrome and it is working there.

**Comment by ashepply** [comment] 2018-10-17 21:37
I'm having the same issue. In Firefox and Safari I can not ```cmd+c```. However, I can right click paste in both browsers. I am running the latest versions as well.

**Comment by javisperez** [comment] 2018-10-18 00:54
Sweet, thanks for the feedbacks guys, ill look into this 💪

**Comment by javisperez** [comment] 2018-10-18 13:55
Just pushed the fix for this, should be deployed in any minute now, thanks again :)

**Closed as completed** 2018-10-18 13:54 UTC

**Comment by scottzirkel** [comment] 2018-10-18 14:14
Works great! Thanks!
